[workspace]
members = ["clock-example", "counter", "failure"]
resolver = "2"

[workspace.dependencies]
borsh = "1.5.5"
solana-account-info = "2.3"
solana-clock = "2.2"
solana-msg = "2.2"
solana-program-entrypoint = "2.3"
solana-program-error = "2.2"
solana-pubkey = "2.3"
solana-sysvar = { version = "2.3", features = ["bincode"] }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
